name: 'Publish to WordPress SVN repository'
description: "Publish to WordPress SVN repository"
inputs:
  svn-username:
    description: "SVN username for authentication"
    required: true
  svn-password:
    description: "SVN password for authentication"
    required: true
  svn-repository:
    description: "Plugin SVN repository URL"
    required: true
  plugin-version:
    description: "Plugin version to deploy"
    required: true
  working-directory:
    description: "Directory to copy files from"
    required: true
  assets-directory:
    description: "Directory containing assets"
    required: false

runs:
  using: 'composite'
  steps:
    - id: setup
      run: |
        sudo apt update
        sudo apt install -y subversion rsync zip
      shell: bash
    - id: deploy
      run: bash ${{ github.action_path }}/deploy.sh
      shell: bash
      env:
        INPUT_SVN_USERNAME: ${{ inputs.svn-username }}
        INPUT_SVN_PASSWORD: ${{ inputs.svn-password }}
        INPUT_PLUGIN_REPOSITORY: ${{ inputs.svn-repository }}
        INPUT_PLUGIN_VERSION: ${{ inputs.plugin-version }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_ASSETS_DIRECTORY: ${{ inputs.assets-directory }}
